### ISSUE TITLE
Test review notes

### ISSUE THREAD

**Issue by kaleocheng** [max-f-z/wiredcraft#1]
Hi Fuqing, I'm Kaleo who talked with you before. 

Thanks for your time to finish this testing.  It's clean and impressive.  just some minor feedback:

## part 2
1. better to ecrypt secret info https://github.com/max-f-z/wiredcraft/blob/master/part2/role/defaults/main.yml#L6 

## part 3
you metioned that you are new to terraform, but actully your tf script is  good.  only some small improvement:
1. same as part2, encrypt the password info
2. use var instead  of hardcode the ip/image
3. maybe consinder to use s3 as tf backend 

## part 4
LGTM for api level. 

for app level,  seems missing logs for redis init   + there is no default timeout, those two make the app kind of hard to debug: if you start the app without redis ready, you will be stuck in there for around 1 min(depends on your system) without any logs info/error msg.   better to  add  a shorter specific timeout like 3s or print the connection info out in every 1 second. also you can add a health check api to expose the redis failure to k8s so you can still start the web server to serve the swagger api instead of exit the whole app. 

## part 5&6
LGTM

**Comment by max-f-z** [comment]
Thanks for reviewing this  @Kaleo.

Yeah, your comments totally make sense.

I guess for Part 2, it can be addressed using ansible vault pretty quick.

For Part 3, as I said terraform is new to me. Plus I have on call duty these two weeks so didn't spend much time on it.
But definitely true if we want to use it in daily work. guess I will spend some time on best practice of terraform.

For Part 4, totally agree adding logs & having timeout on connecting to redis. As for adding custom metrics seems also reasonable, but I think it could be an independent subject since we are enhancing the observability for our app.
Having the metrics running in a separate port also is a good idea. Since we might not want to expose metrics to production. I’m thinking also have configuration for swagger so that in production we can disable it.

Thanks for all the efforts Kaleo. So do you need me to address all those issues mentioned?

**Comment by kaleocheng** [comment]
No need, those are just minor issues, Let's move forward with Winnie, Closing this as done.
